/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static myproject.dbvar.dpass;
import static myproject.dbvar.durl;
import static myproject.dbvar.duser;

public class consumer extends javax.swing.JInternalFrame {

    /**
     * Creates new form consumer
     */
    public consumer() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        s2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        s5 = new javax.swing.JTextArea();
        s3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        s4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("phone");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Consumer ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Address");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel11.setText("Coustomer Information");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        s5.setColumns(20);
        s5.setRows(5);
        jScrollPane1.setViewportView(s5);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("email ");

        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(s1)
                                    .addComponent(s2)
                                    .addComponent(s3)
                                    .addComponent(jScrollPane1)
                                    .addComponent(s4))))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{

            String url = "jdbc:mysql://localhost/store";
            String user="root";
            Connection conn =DriverManager.getConnection(durl ,duser,dpass );
            try{

                String q="insert into consumer values(?,?,?,?,?)";
                PreparedStatement myst = (PreparedStatement) conn.prepareStatement(q);
                myst.setString(1,s1.getText());
                myst.setString(2,s2.getText());
                myst.setString(3,s3.getText());
                myst.setString(4,s4.getText());
                myst.setString(5,s5.getText());
                

                int count = myst.executeUpdate();

                if(count==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "Consumer added successfully");
                    clear();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Consumer not added successfully");
                    clear();
                }

            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in connectivity"+e.getMessage());
            }

            finally
            {

                conn.close();
            }
        }
        catch(SQLException e)
        {

            JOptionPane.showMessageDialog(rootPane,"Cannot connect");

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try{

            Connection conn =DriverManager.getConnection(durl ,duser,dpass );
            try{

                String q="select * from consumer where csid = ?";
                PreparedStatement myst = (PreparedStatement) conn.prepareStatement(q);
                myst.setString(1,s1.getText());
                ResultSet rs =myst.executeQuery();

                if(rs.next())
                {
                    s2.setText(rs.getString(2));
                    s3.setText(rs.getString(3));
                    s4.setText(rs.getString(4));
                    s5.setText(rs.getString(5));
                    jButton3.setEnabled(true);
                    jButton4.setEnabled(true);

                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Consumer not found");

                }

            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in connectivity"+e.getMessage());
            }

            finally
            {

                conn.close();
            }
        }
        catch(SQLException e)
        {

            JOptionPane.showMessageDialog(rootPane,"Cannot connect");

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{

            Connection conn =DriverManager.getConnection(durl ,duser,dpass );
            try{

                String q="delete  from consumer where csid = ?";
                PreparedStatement myst = (PreparedStatement) conn.prepareStatement(q);
                myst.setString(1,s1.getText());

                int count = myst.executeUpdate();

                if(count==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "Consumer deleted successfully");
                    clear();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Consumer not deleted successfully");
                    clear();
                }

                jButton3.setEnabled(false);
                jButton4.setEnabled(false);

            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in connectivity"+e.getMessage());
            }

            finally
            {

                conn.close();
            }
        }
        catch(SQLException e)
        {

            JOptionPane.showMessageDialog(rootPane,"Cannot connect");

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try{

            String url = "jdbc:mysql://localhost/store";
            String user="root";
            Connection conn =DriverManager.getConnection(durl ,duser,dpass );
            try{

                String q="update consumer set cname=?, cphone=?, cemail=?, caddress=? where csid=?";
                PreparedStatement myst = (PreparedStatement) conn.prepareStatement(q);
                myst.setString(1,s2.getText());
                myst.setString(2,s3.getText());
                myst.setString(3,s4.getText());
                myst.setString(4,s5.getText());
                myst.setString(5,s1.getText());

                int count = myst.executeUpdate();

                if(count==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "Supplier updated successfully");
                    clear();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Supplier not updated successfully");
                    clear();
                }

                jButton3.setEnabled(false);
                jButton4.setEnabled(false);

            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in connectivity"+e.getMessage());
            }

            finally
            {

                conn.close();
            }
        }
        catch(SQLException e)
        {

            JOptionPane.showMessageDialog(rootPane,"Cannot connect");

        }
        
        

    }//GEN-LAST:event_jButton4ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        
        
        try{

        
         Connection conn =DriverManager.getConnection(durl ,duser,dpass );
        try{
         
        String q="select *  from consumer ";
        PreparedStatement myst = (PreparedStatement) conn.prepareStatement(q);
        
        
        ResultSet rs =myst.executeQuery();
        
        if(rs.next()==false)
        {
         JOptionPane.showMessageDialog(rootPane, "No Supplier present \n Add Supplier");
         
        }
        
        
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        
        
        }
        catch(SQLException e)
        {        
        JOptionPane.showMessageDialog(rootPane,"Error in connectivity"+e.getMessage());
        }
        
        finally
        {
        
          conn.close();
        }
}
catch(SQLException e)
{

JOptionPane.showMessageDialog(rootPane,"Cannot connect");

}
        
        
                             
    }//GEN-LAST:event_formInternalFrameOpened

private void clear() {
        s1.setText(null);
        s2.setText(null);
        s3.setText(null);
        s4.setText(null);
        s5.setText(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JTextArea s5;
    // End of variables declaration//GEN-END:variables
}
