/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static myproject.dbvar.dpass;
import static myproject.dbvar.durl;
import static myproject.dbvar.duser;

/**
 *
 * @author HP
 */
public class supplier extends javax.swing.JInternalFrame {

    /**
     * Creates new form supplier
     */
    String max;
    public supplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        s2 = new javax.swing.JTextField();
        s3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        s6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        s5 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        s4 = new javax.swing.JTextField();
        s1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("phone");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Address");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("GST ID");

        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Supplier ID");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel11.setText("Supplier Manager");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        s5.setColumns(20);
        s5.setRows(5);
        jScrollPane1.setViewportView(s5);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("email ");

        s1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Supplier ID" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s2)
                                    .addComponent(s3)
                                    .addComponent(s6)
                                    .addComponent(jScrollPane1)
                                    .addComponent(s4)
                                    .addComponent(s1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(s6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{

        String url = "jdbc:mysql://localhost/store";
        String user="root";
         Connection conn =DriverManager.getConnection(durl ,duser,dpass );
        try{
         
        String q="insert into supplier(sname,sphone,smail,saddress,sg) values(?,?,?,?,?)";
        PreparedStatement myst = (PreparedStatement) conn.prepareStatement(q);
        myst.setString(1,s2.getText()); 
        myst.setString(2,s3.getText());
        myst.setString(3,s4.getText());
        myst.setString(4,s5.getText());
        myst.setString(5,s6.getText());
       
        
        int count = myst.executeUpdate();
        
        if(count==1)
        {
         JOptionPane.showMessageDialog(rootPane, "Supplier added successfully");
         sid();
         maxsid();
         clear();
        }
        else
        {
         JOptionPane.showMessageDialog(rootPane, "Supplier not added successfully");
         sid();
         maxsid();
         clear();
        }
        
        
        }
        catch(SQLException e)
        {        
        JOptionPane.showMessageDialog(rootPane,"Error in connectivity"+e.getMessage());
        }
        
        finally
        {
        
          conn.close();
        }
}
catch(SQLException e)
{

JOptionPane.showMessageDialog(rootPane,"Cannot connect");

}
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  
  try{

        
         Connection conn =DriverManager.getConnection(durl ,duser,dpass );
        try{
         
        String q="select * from supplier where sid = ?";
        PreparedStatement myst = (PreparedStatement) conn.prepareStatement(q);
        myst.setString(1,s1.getSelectedItem().toString());
        ResultSet rs =myst.executeQuery();
      
        if(rs.next())
        {
          s2.setText(rs.getString(2));
          s3.setText(rs.getString(3));
          s4.setText(rs.getString(4));
          s5.setText(rs.getString(5));
          s6.setText(rs.getString(6));
          jButton3.setEnabled(true);
          jButton4.setEnabled(true);
          
        }
        else
        {
         JOptionPane.showMessageDialog(rootPane, "Supplier not found");
             
        }
        
        
        }
        catch(SQLException e)
        {        
        JOptionPane.showMessageDialog(rootPane,"Error in connectivity"+e.getMessage());
        }
        
        finally
        {
        
          conn.close();
        }
}
catch(SQLException e)
{

JOptionPane.showMessageDialog(rootPane,"Cannot connect");

}
      

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        check();
        sid();
        maxsid();
        
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{

        
         Connection conn =DriverManager.getConnection(durl ,duser,dpass );
        try{
         
        String q="delete  from supplier where sid = ?";
        PreparedStatement myst = (PreparedStatement) conn.prepareStatement(q);
        myst.setString(1,s1.getSelectedItem().toString());
        
        int count = myst.executeUpdate();
        
        if(count==1)
        {
         JOptionPane.showMessageDialog(rootPane, "Supplier deleted successfully");
         sid();
         maxsid();
         clear();
        }
        else
        {
         JOptionPane.showMessageDialog(rootPane, "Supplier not deleted successfully");
         sid();
         maxsid();
         clear();
        }
        
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        
        
        }
        catch(SQLException e)
        {        
        JOptionPane.showMessageDialog(rootPane,"Error in connectivity"+e.getMessage());
        }
        
        finally
        {
        
          conn.close();
        }
}
catch(SQLException e)
{

JOptionPane.showMessageDialog(rootPane,"Cannot connect");

}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        
             try{

        String url = "jdbc:mysql://localhost/store";
        String user="root";
         Connection conn =DriverManager.getConnection(durl ,duser,dpass );
        try{
         
        String q="update supplier set sname=?, sphone=?, smail=?, saddress=?, sg=? where sid=?";
        PreparedStatement myst = (PreparedStatement) conn.prepareStatement(q);
        myst.setString(1,s2.getText());
        myst.setString(2,s3.getText()); 
        myst.setString(3,s4.getText());
        myst.setString(4,s5.getText());
        myst.setString(5,s6.getText());
        myst.setString(6,s1.getSelectedItem().toString());
       
        
        int count = myst.executeUpdate();
        
        if(count==1)
        {
         JOptionPane.showMessageDialog(rootPane, "Supplier updated successfully");
         sid();
         maxsid();
         clear();
        }
        else
        {
         JOptionPane.showMessageDialog(rootPane, "Supplier not updated successfully");
         sid();
         maxsid();
         clear();
        }
        
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        
        
        }
        catch(SQLException e)
        {        
        JOptionPane.showMessageDialog(rootPane,"Error in connectivity"+e.getMessage());
        }
        
        finally
        {
        
          conn.close();
        }
}
catch(SQLException e)
{

JOptionPane.showMessageDialog(rootPane,"Cannot connect");

}
             
        
    }//GEN-LAST:event_jButton4ActionPerformed
void sid()
    {
        s1.removeAllItems();
        s1.addItem("Choose Supplier ID");
        try{

        String url = "jdbc:mysql://localhost/store";
        String user="root";
         Connection con =DriverManager.getConnection(durl ,duser,dpass );
        try{
         
          String q="select sid from supplier ";
        PreparedStatement myst = (PreparedStatement) con.prepareStatement(q);
        
      
        ResultSet rs = myst.executeQuery();
        
        
        
        
        
        if(rs.next())
        {
          do
          {
           s1.addItem(rs.getString(1));
          }while(rs.next());       
        }
        
          else
           {
             JOptionPane.showMessageDialog(rootPane,"no supplier");   
           }
        }
        
        
        catch(Exception e)
        {        
        JOptionPane.showMessageDialog(rootPane,"Error in connectivity"+e.getMessage());
        }
        
        finally
        {
        
          con.close();
        }
}
catch(Exception e)
{

JOptionPane.showMessageDialog(rootPane,"Cannot connect");

}
        
    }

void maxsid()
    {
        
        try{

        String url = "jdbc:mysql://localhost/store";
        String user="root";
         Connection con =DriverManager.getConnection(durl ,duser,dpass );
        try{
         
          String q="select max(sid) from supplier ";
        PreparedStatement myst = (PreparedStatement) con.prepareStatement(q);
        
      
        ResultSet rs = myst.executeQuery();
        
        
        
        
        
        if(rs.next())
        {
          s1.setSelectedItem(rs.getString(1));
          max=rs.getString(1);
        }
        
          else
           {
             JOptionPane.showMessageDialog(rootPane,"no transaction");   
           }
        }
        
        
        catch(Exception e)
        {        
        JOptionPane.showMessageDialog(rootPane,"Error in connectivity"+e.getMessage());
        }
        
        finally
        {
        
          con.close();
        }
}
catch(Exception e)
{

JOptionPane.showMessageDialog(rootPane,"Cannot connect");

}
        
    }

   void check()
   {
   
    try{

        
         Connection conn =DriverManager.getConnection(durl ,duser,dpass );
        try{
         
        String q="select *  from supplier ";
        PreparedStatement myst = (PreparedStatement) conn.prepareStatement(q);
        
        
        ResultSet rs =myst.executeQuery();
        
        if(rs.next()==false)
        {
         JOptionPane.showMessageDialog(rootPane, "No Supplier present \n Add Supplier");
         
        }
        
        
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        
        
        }
        catch(SQLException e)
        {        
        JOptionPane.showMessageDialog(rootPane,"Error in connectivity"+e.getMessage());
        }
        
        finally
        {
        
          conn.close();
        }
}
catch(SQLException e)
{

JOptionPane.showMessageDialog(rootPane,"Cannot connect");

}
   
   }
  
   void clear()
   {
   
    s1.setSelectedItem(max);
    s2.setText(null);
    s3.setText(null);
    s4.setText(null);
    s5.setText(null);
    s6.setText(null);
    
   }

  
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JTextArea s5;
    private javax.swing.JTextField s6;
    // End of variables declaration//GEN-END:variables

   
    
}
